import numpy as np

from prepare_data import build_windows


ALL_RECORDS = [
    "100", "101", "103", "105", "106", "108", "109",
    "111", "112", "113", "114", "115", "116", "117",
    "118", "119", "121", "122", "123", "124",

    "200", "201", "202", "203", "205", "207", "208",
    "209", "210", "212", "213", "214", "215", "219",
    "220", "221", "222", "223", "228", "230", "231",
    "232", "233", "234",
]


CLASS_NAMES = [
    "normal",
    "ventricular",
    "atrial",
    "other_abnormal",
]


NUM_CLASSES = len(CLASS_NAMES)


def get_record_counts(record_name):
    """
    Count classes generated by one patient/record.
    """

    _, labels = build_windows(record_name)

    labels = np.asarray(labels)

    counts = np.bincount(
        labels,
        minlength=NUM_CLASSES,
    )

    return counts


def distribution(counts):

    total = counts.sum()

    if total == 0:
        return np.zeros(NUM_CLASSES)

    return counts / total


def print_split(
    name,
    records,
    record_counts,
):

    counts = np.sum(
        [
            record_counts[r]
            for r in records
        ],
        axis=0,
    )

    dist = distribution(counts)

    print()
    print("=" * 70)
    print(name)
    print("=" * 70)

    print("Records:")
    print(records)

    print()

    for i, class_name in enumerate(CLASS_NAMES):

        print(
            f"{class_name:20s}"
            f"{counts[i]:8d}"
            f"  {dist[i] * 100:7.2f}%"
        )

    print(
        f"\nTotal windows: {counts.sum()}"
    )


def split_score(
    train_records,
    val_records,
    test_records,
    record_counts,
    target_distribution,
):
    """
    Score a patient-level split.

    Lower = better.

    Gives additional importance to minority-class
    representation, especially class 3.
    """

    train_counts = np.sum(
        [record_counts[r] for r in train_records],
        axis=0,
    )

    val_counts = np.sum(
        [record_counts[r] for r in val_records],
        axis=0,
    )

    test_counts = np.sum(
        [record_counts[r] for r in test_records],
        axis=0,
    )

    # -----------------------------------------------------
    # Every class must exist
    # -----------------------------------------------------

    if np.any(train_counts == 0):
        return float("inf")

    if np.any(val_counts == 0):
        return float("inf")

    if np.any(test_counts == 0):
        return float("inf")

    # -----------------------------------------------------
    # Require reasonable class-3 representation
    # -----------------------------------------------------

    OTHER_CLASS = 3

    if val_counts[OTHER_CLASS] < 100:
        return float("inf")

    if test_counts[OTHER_CLASS] < 100:
        return float("inf")

    # -----------------------------------------------------
    # Distributions
    # -----------------------------------------------------

    train_dist = distribution(
        train_counts
    )

    val_dist = distribution(
        val_counts
    )

    test_dist = distribution(
        test_counts
    )

    # -----------------------------------------------------
    # Per-class weights
    #
    # Give minority classes more importance when
    # searching for representative record splits.
    # -----------------------------------------------------

    class_importance = np.array([
        1.0,   # normal
        1.5,   # ventricular
        2.0,   # atrial
        4.0,   # other abnormal
    ])

    train_error = np.sum(
        class_importance
        * np.abs(
            train_dist
            - target_distribution
        )
    )

    val_error = np.sum(
        class_importance
        * np.abs(
            val_dist
            - target_distribution
        )
    )

    test_error = np.sum(
        class_importance
        * np.abs(
            test_dist
            - target_distribution
        )
    )

    # Validation and test matter more
    score = (
        train_error
        + 2.0 * val_error
        + 2.0 * test_error
    )

    return score


def main():

    print(
        "Calculating per-record class distributions..."
    )

    record_counts = {}

    for record_name in ALL_RECORDS:

        counts = get_record_counts(
            record_name
        )

        record_counts[
            record_name
        ] = counts

        print(
            record_name,
            counts,
        )

    # -----------------------------------------------------
    # Overall distribution
    # -----------------------------------------------------

    total_counts = np.sum(
        list(record_counts.values()),
        axis=0,
    )

    target_distribution = distribution(
        total_counts
    )

    print()
    print("=" * 70)
    print("OVERALL DISTRIBUTION")
    print("=" * 70)

    for i, class_name in enumerate(CLASS_NAMES):

        print(
            f"{class_name:20s}"
            f"{total_counts[i]:8d}"
            f"  "
            f"{target_distribution[i] * 100:7.2f}%"
        )

    # -----------------------------------------------------
    # Random patient-level search
    # -----------------------------------------------------

    rng = np.random.default_rng(
        seed=42
    )

    records = np.array(
        ALL_RECORDS
    )

    # 44 records:
    # 30 train
    # 7 validation
    # 7 test

    n_train = 30
    n_val = 7

    best_score = float("inf")
    best_split = None

    NUM_TRIALS = 100000

    print()
    print(
        f"Searching {NUM_TRIALS} "
        f"patient-level splits..."
    )

    for _ in range(NUM_TRIALS):

        shuffled = rng.permutation(
            records
        )

        train_records = shuffled[
            :n_train
        ].tolist()

        val_records = shuffled[
            n_train:
            n_train + n_val
        ].tolist()

        test_records = shuffled[
            n_train + n_val:
        ].tolist()

        score = split_score(
            train_records,
            val_records,
            test_records,
            record_counts,
            target_distribution,
        )

        if score < best_score:

            best_score = score

            best_split = (
                train_records,
                val_records,
                test_records,
            )

    if best_split is None:
        raise RuntimeError(
            "Could not find a valid split."
        )

    train_records, val_records, test_records = (
        best_split
    )

    print()
    print(
        f"Best score: {best_score:.6f}"
    )

    print_split(
        "TRAIN",
        train_records,
        record_counts,
    )

    print_split(
        "VALIDATION",
        val_records,
        record_counts,
    )

    print_split(
        "TEST",
        test_records,
        record_counts,
    )

    print()
    print("=" * 70)

    print("COPY THESE INTO prepare_data.py")

    print("=" * 70)

    print()
    print(
        "TRAIN_RECORDS =",
        train_records,
    )

    print()
    print(
        "VAL_RECORDS =",
        val_records,
    )

    print()
    print(
        "TEST_RECORDS =",
        test_records,
    )


if __name__ == "__main__":
    main()